// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_master_mcawesomeville = "CgkI7IC_ubMcEAIQAw"; // <GPGSID>
        public const string achievement_baby_steps = "CgkI7IC_ubMcEAIQAQ"; // <GPGSID>
        public const string achievement_shadow_fighter = "CgkI7IC_ubMcEAIQDA"; // <GPGSID>
        public const string achievement_pong_jedi = "CgkI7IC_ubMcEAIQCQ"; // <GPGSID>
        public const string achievement_professional_ponger = "CgkI7IC_ubMcEAIQCg"; // <GPGSID>
        public const string achievement_marine_cruiser_destroyer_inbound = "CgkI7IC_ubMcEAIQBQ"; // <GPGSID>
        public const string leaderboard_dark_mode = "CgkI7IC_ubMcEAIQCA"; // <GPGSID>
        public const string achievement_pong_maniac = "CgkI7IC_ubMcEAIQBA"; // <GPGSID>
        public const string achievement_im_just_so_good = "CgkI7IC_ubMcEAIQCw"; // <GPGSID>
        public const string achievement_drunk = "CgkI7IC_ubMcEAIQBg"; // <GPGSID>
        public const string leaderboard_endless_mode = "CgkI7IC_ubMcEAIQBw"; // <GPGSID>
        public const string achievement_getting_the_hang_of_it = "CgkI7IC_ubMcEAIQAg"; // <GPGSID>

}

