// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class PongManiacResources
{
        public const string leaderboard_endless_mode = "CgkI7IC_ubMcEAIQBw"; // <GPGSID>
        public const string achievement_win_20_times = "CgkI7IC_ubMcEAIQAQ"; // <GPGSID>
        public const string achievement_complete_100_levels = "CgkI7IC_ubMcEAIQAw"; // <GPGSID>
        public const string achievement_complete_all_levels = "CgkI7IC_ubMcEAIQBA"; // <GPGSID>
        public const string achievement_purchase_mcd_mode = "CgkI7IC_ubMcEAIQBQ"; // <GPGSID>
        public const string leaderboard_dark_mode = "CgkI7IC_ubMcEAIQCA"; // <GPGSID>
        public const string achievement_complete_50_levels = "CgkI7IC_ubMcEAIQAg"; // <GPGSID>
        public const string achievement_purchase_drunk_mode = "CgkI7IC_ubMcEAIQBg"; // <GPGSID>

}

